# Configuration Settings for C94-M8P device
ublox_gps_node:
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyACM0
    frame_id: gps
    rtcm:
      subscribe: true
    config_on_startup: false    #Assumed to be configured in u-center

    publish:
      all: true
      rtcm: false
      aid:
        hui: false
      nav:
        posecef: true
        relposned: false