# Configuration Settings for C94-M8P device
ublox_gps_node:
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyACM0
    frame_id: gps
    rtcm:
      subscribe: false
    uart1:
      baudrate: 9600
    config_on_startup: false    #Already configured in u-center