# Configuration Settings for C94-M8P device
ublox_gps_node:
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyACM0
    frame_id: gnss0
    rtcm:
      subscribe: true
    config_on_startup: false    #Assumed to be configured in u-center
    publish:
      all: false
      rtcm: false
      aid:
        hui: false
      nav:
        pvt: true
        posecef: true
        relposned: true