# Configuration Settings for C94-M8P device
ublox_gps_node:
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyACM1
    frame_id: gnss1
    rtcm:
      subscribe: false
    config_on_startup: false    #Already configured in u-center

    publish:
      all: false
      rtcm: true
      aid:
        hui: false
      nav:
        posecef: false
        pvt: true
        relposned: true
        heading: true